import { Board } from "./models/Board"
import { Cell } from "./models/Cell"

export const data = [
  new Board(0, [
    new Cell(0),
    new Cell(1),
    new Cell(2, 'X'),
    new Cell(3, 'O'),
    new Cell(4, 'O'),
    new Cell(5, 'O'),
    new Cell(6, 'X'),
    new Cell(7),
    new Cell(8, 'X'),
  ]
  ),
  new Board(1, [
    new Cell(0),
    new Cell(1),
    new Cell(2),
    new Cell(3),
    new Cell(4),
    new Cell(5),
    new Cell(6),
    new Cell(7),
    new Cell(8),
  ]),
  new Board(2, [
    new Cell(0),
    new Cell(1),
    new Cell(2),
    new Cell(3),
    new Cell(4),
    new Cell(5),
    new Cell(6),
    new Cell(7),
    new Cell(8),
  ]),
  new Board(3, [
    new Cell(0),
    new Cell(1),
    new Cell(2),
    new Cell(3),
    new Cell(4),
    new Cell(5),
    new Cell(6),
    new Cell(7),
    new Cell(8),
  ]),
  new Board(4, [
    new Cell(0),
    new Cell(1),
    new Cell(2),
    new Cell(3),
    new Cell(4),
    new Cell(5),
    new Cell(6),
    new Cell(7),
    new Cell(8),
  ]),
  new Board(5, [
    new Cell(0),
    new Cell(1),
    new Cell(2),
    new Cell(3),
    new Cell(4),
    new Cell(5),
    new Cell(6),
    new Cell(7),
    new Cell(8),
  ]),
  new Board(6, [
    new Cell(0),
    new Cell(1),
    new Cell(2),
    new Cell(3),
    new Cell(4),
    new Cell(5),
    new Cell(6),
    new Cell(7),
    new Cell(8),
  ]),
  new Board(7, [
    new Cell(0),
    new Cell(1),
    new Cell(2),
    new Cell(3),
    new Cell(4),
    new Cell(5),
    new Cell(6),
    new Cell(7),
    new Cell(8),
  ]),
  new Board(8, [
    new Cell(0),
    new Cell(1),
    new Cell(2),
    new Cell(3),
    new Cell(4),
    new Cell(5),
    new Cell(6),
    new Cell(7),
    new Cell(8),
  ]),
]
