import { Board } from "./models/Board"
import { Cell } from "./models/Cell"
import { Player } from "./enums/Player"

export const data = [
  new Board(0, [
    new Cell(0),
    new Cell(1),
    new Cell(2, Player.X),
    new Cell(3, Player.O),
    new Cell(4, Player.O),
    new Cell(5, Player.O),
    new Cell(6, Player.X),
    new Cell(7),
    new Cell(8, Player.X),
  ]
  ),
  new Board(1, [
    new Cell(0),
    new Cell(1, Player.X),
    new Cell(2),
    new Cell(3, Player.X),
    new Cell(4, Player.X),
    new Cell(5, Player.X),
    new Cell(6, Player.O),
    new Cell(7, Player.X),
    new Cell(8, Player.O),
  ]),
  new Board(2, [
    new Cell(0),
    new Cell(1),
    new Cell(2),
    new Cell(3),
    new Cell(4),
    new Cell(5),
    new Cell(6),
    new Cell(7),
    new Cell(8),
  ]),
  new Board(3, [
    new Cell(0),
    new Cell(1),
    new Cell(2, Player.X),
    new Cell(3, Player.O),
    new Cell(4, Player.O),
    new Cell(5, Player.O),
    new Cell(6, Player.X),
    new Cell(7),
    new Cell(8, Player.X),
  ]),
  new Board(4, [
    new Cell(0),
    new Cell(1),
    new Cell(2),
    new Cell(3),
    new Cell(4),
    new Cell(5),
    new Cell(6),
    new Cell(7),
    new Cell(8),
  ]),
  new Board(5, [
    new Cell(0),
    new Cell(1),
    new Cell(2),
    new Cell(3),
    new Cell(4),
    new Cell(5),
    new Cell(6),
    new Cell(7),
    new Cell(8),
  ]),
  new Board(6, [
    new Cell(0),
    new Cell(1),
    new Cell(2, Player.X),
    new Cell(3, Player.O),
    new Cell(4, Player.O),
    new Cell(5),
    new Cell(6, Player.X),
    new Cell(7),
    new Cell(8, Player.X),
  ]),
  new Board(7, [
    new Cell(0),
    new Cell(1),
    new Cell(2),
    new Cell(3),
    new Cell(4),
    new Cell(5),
    new Cell(6),
    new Cell(7),
    new Cell(8),
  ]),
  new Board(8, [
    new Cell(0),
    new Cell(1),
    new Cell(2),
    new Cell(3),
    new Cell(4),
    new Cell(5),
    new Cell(6),
    new Cell(7),
    new Cell(8),
  ]),
]
